name: Packaged Component and Deployment

on:
  #schedule:
   #- cron: '5 * * * *'
  workflow_dispatch:
   inputs:
     componentid:
       description: 'Component ID'
       required: true
       default: ''
     version:
       description: 'Version'
       required: false
       default: '0.00'

jobs:
  preReqs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo Componet ID: ${{ inputs.componentid}}
        echo Version: ${{ inputs.version}}
        
  createPackage:
    runs-on: [ubuntu-latest]
    needs: preReqs
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v37.5.2

      # Runs a set of commands using the runners shell
      - name: Create Packaged Component
        id: createPackage
        run: | 
           compId=${{ inputs.componentid}}
           compCount=1
           compCount=$(echo "$compId" | awk -F "," '{print NF-1}')
           compCount=$((compCount + 1))
           echo Number of Components: $compCount
           for (( _compIdx=1 ; _compIdx <= $compCount ; _compIdx++ )) ; do
              _compId=$(echo $compId | cut -f $_compIdx -d",")
              echo Create Packaged Component for Id: $_compId
           done
          
  deploytoSIT:
    runs-on: [ubuntu-latest]
    needs: createPackage
    environment:
      name: "SIT"
    steps:
      - name: Deploy to SIT Environment
        id: deploytoSIT
        run: | 
           compId=${{ inputs.componentid}}
           compCount=1
           compCount=$(echo "$compId" | awk -F "," '{print NF-1}')
           compCount=$((compCount + 1))
           echo Number of Components: $compCount
           for (( _compIdx=1 ; _compIdx <= $compCount ; _compIdx++ )) ; do
              _compId=$(echo $compId | cut -f $_compIdx -d",")
              echo Deploy to SIT - Component Id: $_compId
           done

  deploytoUAT:
    runs-on: [ubuntu-latest]
    needs:  [createPackage, deploytoSIT]
    environment:
      name: "UAT"
    steps:
      - name: Deploy to UAT Environment
        id: deploytoUAT
        run: | 
           compId=${{ inputs.componentid}}
           compCount=1
           compCount=$(echo "$compId" | awk -F "," '{print NF-1}')
           compCount=$((compCount + 1))
           echo Number of Components: $compCount
           for (( _compIdx=1 ; _compIdx <= $compCount ; _compIdx++ )) ; do
              _compId=$(echo $compId | cut -f $_compIdx -d",")
              echo Deploy to UAT - Component Id: $_compId
           done

  deploytoPRD:
    runs-on: [ubuntu-latest]
    needs:  [createPackage, deploytoSIT, deploytoUAT]
    environment:
      name: "PRD"
    steps:
      - name: Deploy to PRD Environment
        id: deploytoPRD
        run: | 
           compId=${{ inputs.componentid}}
           compCount=1
           compCount=$(echo "$compId" | awk -F "," '{print NF-1}')
           compCount=$((compCount + 1))
           echo Number of Components: $compCount
           for (( _compIdx=1 ; _compIdx <= $compCount ; _compIdx++ )) ; do
              _compId=$(echo $compId | cut -f $_compIdx -d",")
              echo Deploy to PRD - Component Id: $_compId
           done
           
           
