name: Trigger Workflow
on:
  #repository_dispatch:
  #  types: [do-something]
  workflow_dispatch:
   inputs:
     componentid:
       description: 'Component ID'
       required: true
       default: ''
     version:
       description: 'Version'
       required: false
       default: '0.00'
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ inputs.componentid}}
        echo ${{ inputs.version}}
