name: Packaged Component and Deployment
on:
  #repository_dispatch:
  #  types: [do-something]
  workflow_dispatch:
   inputs:
     componentid:
       description: 'Component ID'
       required: true
       default: ''
     version:
       description: 'Version'
       required: false
       default: '0.00'
jobs:
  preReqs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo Componet ID: ${{ inputs.componentid}}
        echo Version: ${{ inputs.version}}
 
  createPackage:
  
    runs-on: [ubuntu-latest]
    needs: preReqs
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v37.5.2

      # Runs a set of commands using the runners shell
      - name: Create Package
        id: createPackage
        run: | 

          compId=${{ inputs.componentid}}
          compCount=1
          compCount=$(echo "$compId" | awk -F "," '{print NF-1}')
          compCount=$((compCount + 1))
          echo Number of Components: $compCount
          
