name: Trigger Workflow
env:
  owner: mazmat-uts
  repo: my-first-repo
on:
  #repository_dispatch:
  #  types: [do-something]
  workflow_dispatch:
   inputs:
    name:
      description: 'Person to greet'
      required: true
      default: 'Azmat'
    home:
     description: 'location'
     required: false
     default: 'Melbourne'
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello $!"
        echo "- in $!"
